# infra/docker-compose.yml
version: '3.8'

services:
  # 1. 数据库
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: model_eval_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. 对象存储 (S3 Compatible)
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # 控制台端口
    volumes:
      - minio_data:/data

  # 3. 消息队列
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # 4. API 服务
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/model_eval_db
      - MINIO_ENDPOINT=minio:9000
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - db
      - minio
      - redis

  # 5. Worker 服务
  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    # 启动 celery worker
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ../:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/model_eval_db
      - MINIO_ENDPOINT=minio:9000
      - REDIS_URL=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    depends_on:
      - db
      - minio
      - redis

  mlflow:
    # image: ghcr.io/mlflow/mlflow:v2.7.1
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      # 让 MLflow 使用我们的 Postgres 存实验数据
      - MLFLOW_BACKEND_STORE_URI=postgresql://user:password@db:5432/model_eval_db
      # 让 MLflow 使用我们的 MinIO 存模型文件 (Artifacts)
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    command: >
      mlflow server
      --backend-store-uri postgresql://user:password@db:5432/model_eval_db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
    depends_on:
      - db
      - minio
volumes:
  postgres_data:
  minio_data: